spring:
  cloud:
    config:
      enabled: false
  data:
    elasticsearch:
      repositories:
        enabled: false
server:
  port: 5000
  servlet:
    context-path: /poc
elastic:
  indexName: foodtruck
  integerFields:
    - Neighborhoods
    - ZipCodes
    - SupervisorDistricts
    - PoliceDistricts
    - FirePreventionDistricts
    - PriorPermit
    - Received
  longFields:
    - locationid
    - cnn
  stringFields:
    - Applicant
    - FacilityType
    - LocationDescription
    - Address
    - blocklot
    - block
    - lot
    - permit
    - Status
    - FoodItems
    - Schedule
    - dayshours
    - NOISent
    - Approved
  floatFields:
    - X
    - Y
    - Latitude
    - Longitude
    - Location
  dateFields:
    - ExpirationDate